// Records what Fluent's reference DOM bindings (@fluent/dom, in jsdom) make
// of a p23 test vector: for every `tests/vectors/*/` holding `page.html` +
// `messages.ftl` (or the directories given), translate the page's
// `data-l10n-id` elements with an en-US bundle and write the translated DOM
// to `fluent.html` next to the inputs.
//
// The Rust test `fluent_oracle` (tests/html_ui.rs) then requires p23 built
// from `page.html` + the bundle to equal p23 built from `fluent.html` with no
// locale. No Node is needed to run the tests.
//
// Run via `scripts/fluent_oracle.sh [VECTOR_DIR ...]` (installs the pinned
// packages on first use).

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { FluentBundle, FluentResource } from "@fluent/bundle";
import { DOMLocalization } from "@fluent/dom";
import { JSDOM } from "jsdom";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../..");
const VECTORS = join(ROOT, "tests/vectors");
const LOCALE = "en-US";

function version(name) {
  const manifest = join(HERE, "node_modules", name, "package.json");
  return JSON.parse(readFileSync(manifest, "utf8")).version;
}

async function translate(vector) {
  const page = readFileSync(join(vector, "page.html"), "utf8");
  const ftl = readFileSync(join(vector, "messages.ftl"), "utf8");
  if (/\{\{|\{%/.test(page)) {
    throw new Error(`${vector}: oracle vectors must be plain HTML (no Tera syntax)`);
  }

  // p23 strips Fluent's bidi isolation marks (U+2068/U+2069); turn them off
  // here instead of comparing around them.
  const bundle = new FluentBundle(LOCALE, { useIsolating: false });
  const errors = bundle.addResource(new FluentResource(ftl));
  if (errors.length) {
    throw new Error(`${vector}: FTL errors: ${errors.map(String).join("; ")}`);
  }

  // fluent-dom reports sanitizer decisions and missing messages through
  // console.warn: keep them, they explain the reference.
  const warnings = [];
  const warn = console.warn;
  console.warn = (...args) => warnings.push(args.join(" "));
  try {
    const dom = new JSDOM(`<!doctype html><html><body>${page}</body></html>`);
    const l10n = new DOMLocalization([], async function* () {
      yield bundle;
    });
    await l10n.translateFragment(dom.window.document.body);
    // The reference is the translated DOM itself, not more instructions.
    for (const element of dom.window.document.querySelectorAll("*")) {
      for (const attr of Array.from(element.attributes)) {
        if (attr.name.startsWith("data-l10n-")) element.removeAttribute(attr.name);
      }
    }
    return { html: dom.window.document.body.innerHTML, warnings };
  } finally {
    console.warn = warn;
  }
}

function vectorsFromArgs() {
  const args = process.argv.slice(2);
  if (args.length) return args.map((arg) => resolve(process.cwd(), arg));
  return readdirSync(VECTORS)
    .map((name) => join(VECTORS, name))
    .filter((dir) => existsSync(join(dir, "page.html")) && existsSync(join(dir, "messages.ftl")))
    .sort();
}

const generator =
  `@fluent/dom ${version("@fluent/dom")}, @fluent/bundle ${version("@fluent/bundle")}, ` +
  `jsdom ${version("jsdom")}; locale ${LOCALE}, useIsolating false`;
for (const vector of vectorsFromArgs()) {
  const { html, warnings } = await translate(vector);
  const comment = (text) => `<!-- ${text.replaceAll("--", "- -")} -->\n`;
  let out = comment(
    `Generated by scripts/fluent_oracle.sh from page.html + messages.ftl (${generator}). Do not edit.`,
  );
  for (const warning of warnings) out += comment(`fluent-dom: ${warning}`);
  writeFileSync(join(vector, "fluent.html"), `${out}${html.trim()}\n`);
  console.log(`${relative(ROOT, vector)}: ${warnings.length} fluent-dom warning(s)`);
  for (const warning of warnings) console.log(`  ${warning}`);
}
